# Generated by Django 5.2 on 2025-06-02 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại')),
            ],
            options={
                'verbose_name': 'Loại quần áo',
                'verbose_name_plural': 'Các loại quần áo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên món đồ')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu sắc')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Thương hiệu')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link ảnh')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Lần sửa cuối')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='app.clothingcategory', verbose_name='Loại')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Món đồ',
                'verbose_name_plural': 'Các món đồ',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bộ đồ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối')),
                ('clothing_items', models.ManyToManyField(blank=True, related_name='outfits', to='app.clothingitem', verbose_name='Các món đồ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bộ đồ',
                'verbose_name_plural': 'Các bộ đồ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
