# Generated by Django 5.2 on 2025-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothing_images/', verbose_name='Ảnh'),
        ),
    ]
